{"name": "Страница авторизации. Переход на страницу регистрации", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver unexpectedly exited. Status code was: 127", "trace": "config = {'browser': 'chrome', 'debug_log': False, 'selenoid': None, 'url': 'http://my_app:8086/', ...}\ntemp_dir = '/tmp/tests/code/ui_myapp/tests/test_ui.py::TestUIUnauthorizedUserAuthPage::test_auth_page_redirect_to_reg_page'\n\n    @pytest.fixture()\n    def driver(config, temp_dir):\n        browser = config['browser']\n        url = config['url']\n        selenoid = config['selenoid']\n        vnc = config['vnc']\n        if selenoid:\n            capabilities = {\n                'browserName': 'chrome',\n                'version': '98.0',\n            }\n            if vnc:\n                capabilities['enableVNC'] = True\n            driver = webdriver.Remote(\n                'http://127.0.0.1:4444/wd/hub',\n                desired_capabilities=capabilities\n            )\n        else:\n>           driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())\n\nbrowser    = 'chrome'\nconfig     = {'browser': 'chrome', 'debug_log': False, 'selenoid': None, 'url': 'http://my_app:8086/', ...}\nselenoid   = None\ntemp_dir   = '/tmp/tests/code/ui_myapp/tests/test_ui.py::TestUIUnauthorizedUserAuthPage::test_auth_page_redirect_to_reg_page'\nurl        = 'http://my_app:8086/'\nvnc        = False\n\ncode/ui_myapp/tools/fixtures.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py:70: in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n        __class__  = <class 'selenium.webdriver.chrome.webdriver.WebDriver'>\n        chrome_options = None\n        desired_capabilities = None\n        executable_path = '/root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver'\n        keep_alive = True\n        options    = None\n        port       = 0\n        self       = <[AttributeError(\"'WebDriver' object has no attribute 'session_id'\") raised in repr()] WebDriver object at 0x7f986e172ca0>\n        service    = <selenium.webdriver.chrome.service.Service object at 0x7f986e172370>\n        service_args = None\n        service_log_path = None\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py:90: in __init__\n    self.service.start()\n        __class__  = <class 'selenium.webdriver.chromium.webdriver.ChromiumDriver'>\n        _ignore_proxy = None\n        browser_name = 'chrome'\n        desired_capabilities = None\n        keep_alive = True\n        options    = <selenium.webdriver.chrome.options.Options object at 0x7f986e172c10>\n        port       = 0\n        self       = <[AttributeError(\"'WebDriver' object has no attribute 'session_id'\") raised in repr()] WebDriver object at 0x7f986e172ca0>\n        service    = <selenium.webdriver.chrome.service.Service object at 0x7f986e172370>\n        service_args = None\n        service_log_path = None\n        vendor_prefix = 'goog'\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n        cmd        = ['/root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver', '--port=41651']\n        count      = 1\n        self       = <selenium.webdriver.chrome.service.Service object at 0x7f986e172370>\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f986e172370>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver unexpectedly exited. Status code was: 127\n\nreturn_code = 127\nself       = <selenium.webdriver.chrome.service.Service object at 0x7f986e172370>\n\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/service.py:110: WebDriverException"}, "description": "\n                                 Тестирование: Авторизация. Переход на страницу регистрации\n                                 Предусловия:\n                                 Шаги:\n                                 1. Нажать через UI на линк регистрации\n                                 Ожидаемый результат:\n                                 Линк действительно ведет на страницу регистрации /reg (+)\n                                 Фактический результат:\n                                 Линк действительно ведет на страницу регистрации /reg\n                ", "attachments": [{"name": "log", "source": "ba8a2ca7-a82c-4dd4-8245-547f7595be35-attachment.txt", "type": "text/plain"}], "start": 1653174746218, "stop": 1653174746218, "uuid": "37e964ba-bfc8-4c69-a944-e0d29e1378d2", "historyId": "bfee7b921779cacd475750fa4fc0aeae", "testCaseId": "abc27d165642f0aed80b3e6a20c9095f", "fullName": "code.ui_myapp.tests.test_ui.TestUIUnauthorizedUserAuthPage#test_auth_page_redirect_to_reg_page", "labels": [{"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "code.ui_myapp.tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "TestUIUnauthorizedUserAuthPage"}, {"name": "host", "value": "ebf8aaa79544"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "code.ui_myapp.tests.test_ui"}]}